apiVersion: v1
kind: Service
metadata:
  name: techchallenge5service
spec:
  selector:
    app: techchallenge5pod
  ports:
    - name: apiproducer-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: apiproducer-https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: rabbitmq-http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rabbitmq-amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: LoadBalancer